title: Jennifer L. Berdahl
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: 
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: What's New
   url: /index.html
 - title: Bio
   url: /bio
 - title: Research
   url: /research
 - title: Teaching
   url: /teaching
 - title: Outreach
   url: /outreach
 - title: Blog
   url: /blog
 - title: Contact
   url: /contact

social:
   github: jberdahl
   twitter: jberdahl
   facebook: 
   email: jennifer.berdahl@gmail.com

google_analytics: 
