title: Jennifer L. Berdahl
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: 
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: What's New
   url: /index.html
 - title: Bio
   url: /bio.html
 - title: Research
   url: /research.html
 - title: Teaching
   url: /teaching.html
 - title: Outreach
   url: /outreach.html
 - title: Blog
   url: /blog.html
 - title: Contact
   url: /contact.html

social:
   github: jberdahl
   twitter: jberdahl
   facebook: 
   email: jennifer.berdahl@gmail.com

google_analytics: 
