title: Jennifer Berdahl
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: 
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: jberdahl
   twitter: jberdahl
   facebook: 
   email: jennifer.berdahl@gmail.com

google_analytics: 
